### ISSUE TITLE
Incorrect calculation of rate in ButtonPusher

### ISSUE THREAD

**Issue by ricerox** [vatbub/commandlineGames#5]
The prompt explaining how ButtonPusher works states that the time to push buttons is one minute. The actual duration is only ten seconds, though.
Still, the calculation for the rate of pushed buttons per second still uses 60 seconds as the duration and the amount of button pushes is divided by 60 (seconds) which leads to a wrong result.

This problem can either be fixed by actually setting the time to wait to one minute/60 seconds or by adjusting the calculation.

**Comment by vatbub** [comment]
Hey :) Thanks for pointing that out :) This is a piece of code that I wrote years ago and I completely forgot about it 🙈  I just fixed it, the timer now runs 60 seconds. The only remaining issue is that if you type "exit" to end the mini game prematurely, the rate is still calculated based on 60 seconds.

Cheers :)
